---

- name: add vscode apt key
  ansible.builtin.apt_key:
    url: "{{ vscode_apt_key }}"

- name: add vscode repo
  ansible.builtin.apt_repository:
    repo: "{{ vscode_repo }}"
    state: present
    filename: vscode

- name: install latest visual studio code
  ansible.builtin.apt:
    name: code
    force_apt_get: yes

- name: install some popular vscode extensions
  ansible.builtin.command: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"
  become: yes
  become_user: "{{ local_username }}"

...
