---

- name: install vim apt packages
  apt:
    name: "{{ vim_apt_packages }}"
    state: present
    force_apt_get: yes

- name: Set default text editor to vim
  alternatives:
    name: editor
    path: /usr/bin/vim.basic

- block:
    - name: clone amix vimrc git repo
      git:
        repo: "{{ vim_amix_vimrc_url }}"
        dest: "~{{ local_username }}/.vim_runtime"
        depth: 1

    - name: install amix vimrc
      shell: "sh ~/.vim_runtime/install_awesome_vimrc.sh"

    - name: Install indentLine plugin
      git:
        repo: "{{ vim_indentline_plugin_url }}"
        dest: "~{{ local_username }}/.vim_runtime/my_plugins/indentLine"

  become: yes
  become_user: "{{ local_username }}"

- block:
    - name: create vim undo directory
      file:
        path: "~{{ local_username }}/.vim/undodir"
        state: directory
        mode: '0775'

    - name: add custom vim config
      copy:
        src: my_configs.vim
        dest: "~{{ local_username }}/.vim_runtime/my_configs.vim"
        mode: '0644'
        force: yes
        backup: yes

  become: yes
  become_user: "{{ local_username }}"

...
